name: CI/CD pipeline
on: 
  push:
    branches:
    - main
    - feature/*
    pull_requests:
      types: [opened, synchronize, closed]
    schedule:
    - cron: '0 0 * * *'  # run daily at midnight 
env: 
  ENVIRONMENT: production
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
    - name: checkout code
      uses: actions/checkour@v3
    - name: Setup nodejs
      uses: actions/setup-node@v2
      with: 
        node-version: '14.x'
    - name: Install dependencies
      run: npm install
    - name: Build app
      run: npm run build
    - name: run tests
      run: npm test 
    - name: Deploy to production
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |
        echo "deploying to prod"
    - name: Notify on pull request
      if: ${{ github.event_name == 'pull_request' }}
      run: echo "a pull request was ${{ github.event.action }} "
    - name: Nightly cleanup
      if: ${{ github.event_name == 'schedule'}}
      run: | 
        echo "running nightly cleanup"
        npm uninstall 
