name: Hello world workflow

on:
  push:
    branches:
    - main
    - feature/*
  pull_request:
    branches:
    - main
  schedule:
    - cron: '*/2 * * * *'  # run every 2min
  # workflow_dispatch:

jobs: 
  hello: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: helloworld
      run: echo "hello"
      shell: bash
  midJob:
    runs-on: ubuntu-latest
    steps:
    - name: push to repo
      if: ${{github.event_name == 'push '}}
      run: |
        echo "this is a push event"
        echo "push task done"
      shell: bash
    - name: nightly job
      if: ${{ github.event_name == 'schedule'}}
      run: |
        echo "this is a nightly job"
  goodbye:
    runs-on: ubuntu-latest
    steps: 
    - name: goodbyeworld
      run: echo "goodbye world!!"
      shell: bash